/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "Platform_Types.h"
#include "BIT_MATH.h"

#define RCC_BASE             0x40021000
#define GPIO_PORTA_BASE      0x40010800

#define RCC_APB2_EN          *((vuint32_t *)(RCC_BASE + 0x18))
#define GPIO_PORTA_CRH       *((vuint32_t *)(GPIO_PORTA_BASE + 0x04))
#define GPIO_PORTA_ODR       *((vuint32_t *)(GPIO_PORTA_BASE + 0x0c))



int main(void)
{
	SET_BIT(RCC_APB2_EN,2);     // Enable RCC Clock for Port A
	GPIO_PORTA_CRH &= 0xff0fffff; // Get them 0 first before change it
	GPIO_PORTA_CRH |= 0x00200000; // Now we can set 2 safely for pin13 mode

	while (1)
	{
		/* Toggle Pin 13 */
		SET_BIT(GPIO_PORTA_ODR,13);
		for(int i = 0 ;i < 500 ; i++);
		CLR_BIT(GPIO_PORTA_ODR,13);
		for(int i = 0 ;i < 500 ; i++);
	}

	return 0;
}
